### ISSUE TITLE
Pure python implementation

### ISSUE THREAD

**Issue by bachp** [telehash/e3x-python#1]
Hi I'm interested in creating a pure python implementation of telehash.
It would be nice if the python bindings for telehash-c and the pure telehash-python implementation would have a compatible api. So people could just switch them out. So they could use the maybe faster telehash-c binding and fall back to the pure python version if necessary.

What you think about this proposal?

**Comment by dvanduzer** [comment]
My current plan is to follow something like [cryptography.io's](https://cryptography.io/en/latest/) approach and have a "backend" interface that will make it easy to switch out support.

Right now I've only updated the pure Python implementation I was working on to support hashname and LOB. I'll get that into GitHub before the weekend is over and you can take a look at that and see how it fits in with your notions.

I wasn't planning on doing much more in pure Python until I had the API figured out, so if you hop on the Slack, we can chat in greater detail.

**Comment by dvanduzer** [comment]
You can take a look at [plinth](https://github.com/telehash/plinth) but most of that isn't going to survive to my v3 implementation. This weekend I planned to create a telehash-python repo that would wrap e3x-python and plinth into a common user-facing API. And to cheat for now, e3x-python was probably just going to wrap the C crypto implementation until I had more time to re-evaluate pure Python crypto.

**Comment by gulfpearl** [comment]
Hi, do you plan on putting anything on github for this?

**Comment by dvanduzer** [comment]
See previous comment re: [plinth](https://github.com/telehash/plinth).
